
# Compose file for development

services:
  web:
    container_name: web
    build: 
      context: web
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 8080:3000
    networks:
      - tidytube-dev
  server:
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/app
    ports:
      - 8000:3000
    networks:
      - tidytube-dev

networks:
  tidytube-dev:
