
# Compose file for development

services:
  # Site
  web:
    container_name: web
    build: 
      context: web
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 8080:3000
    networks:
      - tidytube-dev

  # Server
  server:
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/app
    ports:
      - 8000:3000
    networks:
      - tidytube-dev

  # DB
  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    command: 
      - sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    volumes:
      - ./redis/redis-data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - tidytube-dev
    env_file:
      - server/.env
    

networks:
  tidytube-dev:
