name: ci-config

on:
  push:
    branches:
      - main
    paths:
      - "./docker-compose.yml"
      - "deploy.sh"

  workflow_dispatch: 

jobs:
  alert_cd_action:
    runs-on: ubuntu-latest

    steps:
      - name: Alert CD action
        run: echo Config changed so alert CD action

