name: ci-server

on:
  push:
    branches:
      - main
    paths: 
      - server/**

  workflow_dispatch:

jobs:
  push_server_container:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CONTAINER_TOKEN }}
    
    - name: Build and publish new server image
      uses: docker/build-push-action@v6
      with: 
        context: server
        tags: kakajuro/tidytube-server:latest
        push: true  