name: ci-web

on:
  push:
    branches:
      - main
    paths: 
      - web/**

  workflow_dispatch:

jobs:
  push_web_container:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CONTAINER_TOKEN }}
    
    - name: Build and publish new web image
      uses: docker/build-push-action@v6
      with: 
        context: web
        tags: kakajuro/tidytube-web:latest
        push: true 